### ISSUE TITLE
After-party promotional collateral/email blast

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#158] opened 2016-07-18 23:07 UTC

**Comment by jhibbets** [comment] 2016-09-15 02:19
For those not on the call this week, we decided to call this a networking event instead of an after party.

**Comment by lenaecb** [comment] 2016-09-19 10:35
@dtraleigh - also how can we promote this out? Social media, email blast to attendee list?

**Comment by dtraleigh** [comment] 2016-09-19 11:32
For Thursday night, I suggest we point people to London Bridge pub. This is
very casual though so it's not menlant to be publicized. Let's mention it
at the event on Thursday. It's not like they are waiting for us or anything.

Friday night, we have the Buku lounge area (still waiting for the final
approval from them) from 5-7pm and heavy apps will be served for us. I
suggest we add this to the schedule and can promote it everywhere as an
addition to your ticket.

On Sep 19, 2016 6:35 AM, "lenaecb" notifications@github.com wrote:

@dtraleigh https://github.com/dtraleigh - also how can we promote this
out? Social media, email blast to attendee list?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/codeforraleigh/CityCampNC/issues/158#issuecomment-247960285,
or mute the thread

**Comment by lenaecb** [comment] 2016-09-19 13:02
Ok, so hold off on pushing anything out for that till potentially Wed and Thurs? Don't want to push out any after even gathering till we're all set. Do you think getting the info in the schedule and pushing via social media and email blast to attendees is enough?

**Comment by ChrisTheDBA** [comment] 2016-09-19 13:07
would also mention it at the event 
Chris Mathews

On Mon, Sep 19, 2016 9:02 AM, lenaecb notifications@github.com
wrote:
Ok, so hold off on pushing anything out for that till potentially Wed and Thurs?
Don't want to push out any after even gathering till we're all set. Do you think
getting the info in the schedule and pushing via social media and email blast to
attendees is enough?

**Comment by dtraleigh** [comment] 2016-09-19 15:16
Thursday night drinks, let's just mention it at the event.

The Buku networking event, I just asked them to please get back to me ASAP
that we are good to go. Once they say we are set, we can push this piece
out all over. I sent them a signed contract with payment info but have not
gotten a response yet since Thursday morning. I just want them to OK it.

**Comment by dtraleigh** [comment] 2016-09-19 15:33
Awesome. Got my answer.

We are good to go for Buku as they have confirmed.

Closing this issue but let me know if anything else is needed to promote
this.

**Closed as completed** 2016-09-22 00:23 UTC
Labels: Communications
